### PR TITLE
Add filter functionality and fix minor UI issues

### LINKED ISSUE #32: Unit search filter functionality
Only show the filters when filter icon is tapped.
- [x] Add a filter icon in the search bar from Google Fonts because it is imported already :) 
- [x] Only display the filters pop up when the filter icon is clicked
- [x] Remove filters pop up it is tapped when visible AND on user input (if the user types something remove it because the units search pop up will appear as per #35)
- [x] Add a "clear all" button on the top right of the filters pop up
- [x] "Clear all" button will clear all selections

Currently:
Screenshot 2024-05-29 at 11 13 18 AM

Prototype:
Screenshot 2024-05-29 at 11 13 06 AM

### PR DESCRIPTION
**Pull request by jennifermtan**
Fix #32 and #54.

### CODE REVIEW

File: app/units/page.jsx [hunk 1]
```diff
@@ -1,109 +1,132 @@
...
+    const toggleFilter = () => {
+        setIsFilterVisible(!isFilterVisible);
+    };
+
+    const handleInputChange = () => {
+        setIsFilterVisible(false);
+    };
+
+    const clearForm = () => {
+        document.querySelector(".searchFilter").reset();
```
Comment (GoodGameRuler) [inline app/units/page.jsx:17]: Instead of using reset. Conditionally add CSS based on the state, that changes the height of the accordion to 0, and then add a transition with this to make it look nice.  Perhaps also apply this to the colour change implemented #31. 

Relevant Links:
- [Conditional CSS](https://stackoverflow.com/questions/30533171/conditionally-applying-class-attributes-in-react).
- [Transition](https://developer.mozilla.org/en-US/docs/Web/CSS/transition).

**Review by GoodGameRuler — CHANGES_REQUESTED** [review]

File: app/units/page.jsx (hunk 1 above)
Comment (jennifermtan) [reply app/units/page.jsx:17]: Do you mean add the transition for the colour change?

Comment (GoodGameRuler) [reply app/units/page.jsx:17]: Mb, I wanted a transition, but we can do that when we move to shadow UI. Perhaps could you create an issue to migrate?

**Review by GoodGameRuler — APPROVED** [review]
